slam_toolbox:
  ros__parameters:
    use_sim_time: false
    mode: 'mapping'  # Use 'localization' if using a pre-built map
    map_file_name: ''
    map_start_pose: [0.0, 0.0, 0.0]
    odom_frame: 'odom'
    map_frame: 'map'
    base_frame: 'base_link'
    scan_topic: '/scan'
    update_upon_vanishing: true
    publish_tf: true
    resolution: 0.05
    transform_publish_period: 0.05
    map_update_interval: 5.0
    max_laser_range: 20.0
    minimum_travel_distance: 0.2
    minimum_travel_heading: 0.174  # ~10 degrees in radians
    use_scan_matching: true
    # Add more parameters as needed for your environment
