slam_toolbox:
  ros__parameters:
    use_sim_time: false
    slam_toolbox:
      solver_plugin: solver_plugins::CeresSolver
      ceres_linear_solver: SPARSE_NORMAL_CHOLESKY
      ceres_preconditioner: SCHUR_JACOBI
      ceres_trust_strategy: LEVENBERG_MARQUARDT
      ceres_loss_function: None
    map_file_name: my_map
    mode: mapping
    map_start_pose: [0.0, 0.0, 0.0]
    # Other parameters as needed
